version: 2.1
jobs:
  zookeeper:
    docker:
      - image: simbioseventures/zookeeper:infra
        auth:
          username: simbioseuser  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - run: echo ok

  kafka:
    docker:
      - image: simbioseventures/kafka:infra
        auth:
          username: simbioseuser  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - run: echo ok
  
  shannondbpresto:
    docker:
      - image: simbioseventures/shannondb-presto:infra-dc1
        auth:
          username: simbioseuser  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - run: echo ok

  mysql:
    docker:
      - image: mysql:8.0.17
    steps:
      - run: echo ok

  postgres:
    docker:
      - image: postgres:12
    steps:
      - run: echo ok

  aerospike:
    docker:
      - image: aerospike/aerospike-server
    steps:
      - run: echo ok

  api:
    docker:
      - image: simbioseventures/api-airflow-kong:infra-dc1
        auth:
          username: simbioseuser  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - run: echo ok



workflows:
  version: 2.1
  DOCKER:
    jobs:
      - zookeeper
      - mysql
      - postgres
      - aerospike

      - kafka:
          requires:
            - zookeeper

      - shannondbpresto:
          requires:
            - kafka
      - api:
        requires:
          - shannondb-presto
