version: 2
jobs:
 build:
   machine: true
   steps:
     # - checkout
    - run: |
         docker login -u simbioseuser -p s1mbi0seg1ts3gur@nรง@
         docker run -d --name zookeper simbioseventures/zookeeper:infra